= Version 2.2 (07-03-2019)

This version adds three new connectors:

- https://docs.xill.io/#connector-s3[S3]
- https://docs.xill.io/#connector-wordpress[WordPress]
- https://docs.xill.io/#connector-gitlab[GitLab]

== 2.2.31 - GitLab Connector read operations

A new connector is released: https://docs.xill.io/#connector-gitlab[GitLab].

This is a read-only connector.

== 2.2.22 - Three-part relational scopes

Support for three-part relational scopes have been added. The previous valid scope values still work and map to equivalent three-part relational scope. For more information see https://docs.xill.io/#_scopes_for_entities[Scopes for Entities].

== 2.2.21 - Add Bookmark data type to Box connector

Support for performing operations on the Bookmark data type in the Box connector has been added. This data type
is also known as a Web Link.

== 2.2.20 - Simplify authentication flow

The authentication flow has been simplified to allow retrieving tokens by using the `app` client id instead of your
tenant client id and secret.

== 2.2.19 - S3 Connector read operations

A new connector is released: https://docs.xill.io/#connector-s3[S3].

This is a read-only connector.

== 2.2.12 - WordPress Connector write operations

Write capabilities have been added to the WordPress connector. It is now possible to create, update, and delete pages,
posts, and media in WordPress.

== 2.2.10 - Add Error Header

Responses now return the `Error-ID` header when an error occurs. This header can be reported to our support department
for faster support on our cloud environment.

== 2.2.7 - WordPress Connector read operations

A new connector is released: https://docs.xill.io/#connector-wordpress[WordPress].

This is a read-only connector.
