= Version 2.2 (current)

This version adds two new connectors:

- https://docs.xill.io/#connector-s3[S3]
- https://docs.xill.io/#connector-wordpress[WordPress]

== 2.2.20 - Simplify authentication flow

The authentication flow has been simplified to allow retrieving tokens by using the `app` client id instead of your
tenant client id and secret.

== 2.2.19 - S3 Connector read operations

A new connector is released: https://docs.xill.io/#connector-s3[S3].

This is a read-only connector.

== 2.2.12 - WordPress Connector write operations

Write capabilities have been added to the WordPress connector. It is now possible to create, update, and delete pages,
posts, and media in WordPress.

== 2.2.10 - Add Error Header

Responses now return the `Error-ID` header when an error occurs. This header can be reported to our support department
for faster support on our cloud environment.

== 2.2.7 - WordPress Connector read operations

A new connector is released: https://docs.xill.io/#connector-wordpress[WordPress].

This is a read-only connector.
