= Version 2.9 (current)

Version 2.9.0 adds a new decorator to the Entity structure: https://docs.xill.io/#decorator_workflow[Workflow decorator].

This connector furthermore adds the https://docs.xill.io/#connector-drupal[Drupal connector].

== 2.9.10 - Drupal connector write operations

This version adds write functionality to the Salesforce Knowledge connector. It furthermore adds pagination support to the Drupal connector.

== 2.9.8 - OpenText pagination support

The OpenText connector now supports the pagination feature.

== 2.9.7 - Drupal connector read operations

This version adds the Drupal connector. This connector supports only read functionality.

== 2.9.3 - Redesign of configuration manager

The configuration manager and landing page have been redesigned to suit Xillio's new house style.

== 2.9.0 - Added workflow decorator

The workflow decorator signifies the state of the entity in the workflow of the target system. In web content management systems (WCMs), this is often used to denote the state of publication; draft or published. This decorator is implemented in the WordPress and Zendesk connector with this release.

